export const jwtConstants = {
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_PUBLIC: process.env.ACCESS_TOKEN_PUBLIC,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_PUBLIC: process.env.REFRESH_TOKEN_PUBLIC,
};
